const ORGANIZATION_TYPES = [
  "UNIVERSITY",
  "PME",
  "ISP",
  "DATACENTER",
  "GOVERNMENT",
  "STARTUP",
  "NGO",
  "OTHER",
];

const NODE_TIERS = ["T1", "T2", "T3"];

const LOCAL_NODE_STATUSES = ["ACTIVE", "MAINTENANCE", "DEGRADED", "OFFLINE"];

const CAPABILITY_ATTACK_TYPES = [
  "UDP_FLOOD",
  "SYN_FLOOD",
  "HTTP_FLOOD",
  "DNS_AMPLIFICATION",
  "NTP_AMPLIFICATION",
  "SLOWLORIS",
  "ICMP_FLOOD",
  "GENERIC",
];

const PEER_STATUSES = ["ACTIVE", "INACTIVE", "MAINTENANCE", "SUSPECTED", "BANNED"];

const MEMBERSHIP_STATUSES = ["PROBATION", "CONFIRMED", "SUSPENDED", "EXPELLED"];

const RELATIONSHIP_TYPES = ["DIRECT_NEIGHBOR", "KNOWN_PEER", "DISCOVERED"];

const HEARTBEAT_REPORTED_STATUSES = ["ACTIVE", "DEGRADED", "UNDER_ATTACK", "BUSY"];

const ATTACK_TYPES = [
  "UDP_FLOOD",
  "SYN_FLOOD",
  "HTTP_FLOOD",
  "DNS_AMPLIFICATION",
  "NTP_AMPLIFICATION",
  "SLOWLORIS",
  "MULTI_VECTOR",
  "UNKNOWN",
];

const ATTACK_STATUSES = [
  "DETECTED",
  "ANALYZING",
  "MITIGATING_LOCAL",
  "ESCALATED_TO_COALITION",
  "MITIGATED",
  "ENDED",
  "UNMITIGATED",
];

const ATTACK_SEVERITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];

const TRUST_LEVELS = ["GOLD", "SILVER", "BRONZE", "SUSPECT", "BANNED"];

const RECIPROCITY_TRANSACTION_TYPES = [
  "CREDIT_EARNED",
  "CREDIT_SPENT",
  "BONUS_PROACTIVE",
  "PENALTY_FALSE_ALERT",
  "PENALTY_BROKEN_PROMISE",
  "ADJUSTMENT",
];

const VIOLATION_TYPES = [
  "FREE_RIDING",
  "FALSE_ALERT",
  "CAPACITY_OVERSTATE",
  "BROKEN_PROMISE",
  "SUSPICIOUS_BEHAVIOR",
  "PROTOCOL_VIOLATION",
];

const VIOLATION_SEVERITIES = ["WARNING", "MINOR", "MAJOR", "CRITICAL"];

const SANCTION_TYPES = [
  "NONE",
  "WARNING_SENT",
  "PRIORITY_LOWERED",
  "CAPACITY_LIMITED",
  "TEMP_SUSPENSION",
  "PERMANENT_BAN",
];

const HELP_DIRECTIONS = [
  "OUTBOUND_REQUEST",
  "INBOUND_REQUEST",
  "OUTBOUND_OFFER",
  "INBOUND_OFFER",
];

const HELP_STATUSES = [
  "REQUESTED",
  "OFFERED",
  "NEGOTIATING",
  "ACCEPTED",
  "REJECTED",
  "ACTIVE",
  "COMPLETED",
  "FAILED",
  "CANCELLED",
  "EXPIRED",
];

const TUNNEL_TYPES = ["GRE", "VXLAN", "IPSEC", "BGP_FLOWSPEC"];

const MESSAGE_TYPES = [
  "HELLO",
  "HEARTBEAT",
  "CAPABILITY_ADV",
  "PEER_DISCOVER",
  "GOODBYE",
  "ALERT",
  "HELP_REQUEST",
  "HELP_OFFER",
  "HELP_ACCEPT",
  "HELP_REJECT",
  "TRAFFIC_REDIRECT",
  "ATTACK_OVER",
  "STATUS_REPORT",
  "INCIDENT_LOG",
];

const MESSAGE_DIRECTIONS = ["SENT", "RECEIVED"];

const MESSAGE_PRIORITIES = ["LOW", "NORMAL", "HIGH", "CRITICAL"];

const MESSAGE_PROCESSING_RESULTS = [
  "PROCESSED",
  "REJECTED",
  "FORWARDED",
  "EXPIRED",
  "ERROR",
];

const AUDIT_EVENT_TYPES = [
  "PEER_ADDED",
  "PEER_REMOVED",
  "PEER_BANNED",
  "TRUST_LEVEL_CHANGED",
  "POLICY_CHANGED",
  "CERTIFICATE_RENEWED",
  "AUTH_FAILURE",
  "INVALID_MESSAGE",
  "ESCALATION_TRIGGERED",
  "MANUAL_OVERRIDE",
  "SYSTEM_CONFIG_CHANGE",
];

const AUDIT_SEVERITIES = ["INFO", "WARNING", "ERROR", "CRITICAL"];

module.exports = {
  ATTACK_SEVERITIES,
  ATTACK_STATUSES,
  ATTACK_TYPES,
  AUDIT_EVENT_TYPES,
  AUDIT_SEVERITIES,
  CAPABILITY_ATTACK_TYPES,
  HEARTBEAT_REPORTED_STATUSES,
  HELP_DIRECTIONS,
  HELP_STATUSES,
  LOCAL_NODE_STATUSES,
  MEMBERSHIP_STATUSES,
  MESSAGE_DIRECTIONS,
  MESSAGE_PRIORITIES,
  MESSAGE_PROCESSING_RESULTS,
  MESSAGE_TYPES,
  NODE_TIERS,
  ORGANIZATION_TYPES,
  PEER_STATUSES,
  RECIPROCITY_TRANSACTION_TYPES,
  RELATIONSHIP_TYPES,
  SANCTION_TYPES,
  TRUST_LEVELS,
  TUNNEL_TYPES,
  VIOLATION_SEVERITIES,
  VIOLATION_TYPES,
};
